source 'https://rubygems.org'
ruby '2.5.3'
group :development do
  gem 'capistrano', '~> 3.6.1'
  gem 'capistrano-bundler', '~> 1.2'
end
gem 'rake', '~> 13.0'
gem 'pry'
gem 'sinatra', '~> 2.0'
gem 'rerun'
gem 'pg', '~> 0.20'
gem 'thin', '~> 1.7'
gem 'sequel', '~> 4.47'
gem 'god', '~> 0.13'
gem 'excon', '~> 0.59'
gem 'levenshtein', '~> 0.2.2'
gem 'pry-byebug'
